### ISSUE TITLE
Would this also solve updating only part of a page?

### ISSUE THREAD

**Issue by Haroenv** [jakearchibald/navigation-transitions#1]
Let's say you've got a header and some other static parts on a page. Nowadays you'd fetch the new content with `fetch` and replace the relevant dom with the new content. Would it make sense to use `'navigate'` and somehow only get some of the content you'd then embed on a certain place on the page, but still be able to go to that page regularly and get the whole document.

**Comment by jakearchibald** [comment]
I think this is out of scope. Once you have to deal with state between the fresh/non-fresh content, you kinda have to dig into `pushState`.

**Comment by Haroenv** [comment]
Makes sense. Thanks for your answer
