### ISSUE TITLE
Client side rendered apps?

### ISSUE THREAD

**Issue by oliviertassinari** [jakearchibald/navigation-transitions#11]
> often leading developers to use large frameworks where they aren't needed

Reading through the *README*, I feel like this API is primarily targeting **server-side** rendered apps.
I have been using a [transitions library](https://github.com/doctolib/react-router-transitions) to solve this very same issue.
I'm not sure what the big picture is.
Do you confirm that this new API wouldn't help for **client side** rendered apps?

**Comment by jakearchibald** [comment]
I confirm that this is not for transitions that are not full page navigations.

I'm not sure what client-rendered transitions need beyond the animation API.
