### ISSUE TITLE
Could we use CSS to make transitions?

### ISSUE THREAD

**Issue by jeffersonmourak** [jakearchibald/navigation-transitions#13]
Using CSS we can create more complex animations, also the developers can create your own styles, or reuse styles created to your application.

**Comment by jakearchibald** [comment]
In the examples I use web animations, but you could set class names instead if you want. Is that what you mean?

**Comment by jeffersonmourak** [comment]
Yes, and use the selectos to animate each element, and make a lot of amazing animations.

**Comment by jakearchibald** [comment]
Well, there's no animation that CSS can do that web animations cannot, so adding something CSS-specific won't expand possibilities.

Are you happy with just setting class names in the navigate event?

**Comment by jeffersonmourak** [comment]
Yes 😄

**Comment by jakearchibald** [comment]
Boom!
