### ISSUE TITLE
IE 4 Prior Art

### ISSUE THREAD

**Issue by stowball** [jakearchibald/navigation-transitions#28]
You're probably aware, but IE 4 introduced this feature at a `meta` page level via filters. It might be worth looking at what filters were available and how they could possibly translate to a modern SPA https://msdn.microsoft.com/en-us/library/ms532847(v=vs.85).aspx#Interpage_Transition

**Comment by jakearchibald** [comment]
I'm aware. The idea is to enable something beyond a predefined set of filters.
