### ISSUE TITLE
Stacking contexts

### ISSUE THREAD

**Issue by appsforartists** [jakearchibald/navigation-transitions#8]
You mention that whichever document has the highest `z-index` ends up in front.  Does this mean each document is its own stacking context?

Put another way, can the elements in the documents be interleaved, or are they effectively siloed into their respective document's z spaces?

**Comment by jakearchibald** [comment]
Nah, they'd definately have their own stacking context. I'll add something to clarify that.

**Comment by jakearchibald** [comment]
Fixed in cf02cc835431bbe098823dc46e5b1d5a7f1a973e
